ci: create/update stack based on status

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -45,10 +45,36 @@ execute_cloudformation:
   stage: execute_cloudformation
   script:
     - aws --version
-    - aws cloudformation deploy --template-file ./infrastructure/init.yaml --stack-name PreDeployStack --capabilities CAPABILITY_NAMED_IAM
-    - aws cloudformation wait stack-create-complete --stack-name PreDeployStack
+    # Check if PreDeployStack exists
+    - STACK_STATUS=$(aws cloudformation describe-stacks --stack-name PreDeployStack --query "Stacks[0].StackStatus" --output text 2>/dev/null)
+    - if [ "$STACK_STATUS" = "REVIEW_IN_PROGRESS" ] || [ "$STACK_STATUS" = "CREATE_IN_PROGRESS" ] || [ "$STACK_STATUS" = "UPDATE_IN_PROGRESS" ] || [ "$STACK_STATUS" = "ROLLBACK_IN_PROGRESS" ]; then echo "PreDeployStack is in progress state"; exit 1; fi
+    - if [ "$STACK_STATUS" = "DELETE_IN_PROGRESS" ] || [ "$STACK_STATUS" = "DELETE_COMPLETE" ]; then echo "PreDeployStack is being deleted or deleted"; STACK_STATUS=""; fi
+    - if [ -z "$STACK_STATUS" ]; then
+        aws cloudformation deploy --template-file ./infrastructure/init.yaml --stack-name PreDeployStack --capabilities CAPABILITY_NAMED_IAM;
+        aws cloudformation wait stack-create-complete --stack-name PreDeployStack;
+      else
+        aws cloudformation update-stack --template-file ./infrastructure/init.yaml --stack-name PreDeployStack --capabilities CAPABILITY_NAMED_IAM;
+        aws cloudformation wait stack-update-complete --stack-name PreDeployStack;
+      fi
     - aws s3 cp Lambdas/output/ s3://csci-5410-s24-sdp-5-lambda-code/ --recursive
-    - aws cloudformation deploy --template-file ./infrastructure/output.yaml --stack-name ApiDeploymentStack --capabilities CAPABILITY_NAMED_IAM
-    - aws cloudformation wait stack-create-complete --stack-name ApiDeploymentStack
+   # Check if ApiDeploymentStack exists
+    - STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ApiDeploymentStack --query "Stacks[0].StackStatus" --output text 2>/dev/null)
+    - if [ "$STACK_STATUS" = "REVIEW_IN_PROGRESS" ] || [ "$STACK_STATUS" = "CREATE_IN_PROGRESS" ] || [ "$STACK_STATUS" = "UPDATE_IN_PROGRESS" ] || [ "$STACK_STATUS" = "ROLLBACK_IN_PROGRESS" ]; then echo "ApiDeploymentStack is in progress state"; exit 1; fi
+    - if [ "$STACK_STATUS" = "DELETE_IN_PROGRESS" ] || [ "$STACK_STATUS" = "DELETE_COMPLETE" ]; then echo "ApiDeploymentStack is being deleted or deleted"; STACK_STATUS=""; fi
+    - if [ -z "$STACK_STATUS" ]; then
+        aws cloudformation deploy --template-file ./infrastructure/output.yaml --stack-name ApiDeploymentStack --capabilities CAPABILITY_NAMED_IAM;
+        aws cloudformation wait stack-create-complete --stack-name ApiDeploymentStack;
+      else
+        aws cloudformation update-stack --template-file ./infrastructure/output.yaml --stack-name ApiDeploymentStack --capabilities CAPABILITY_NAMED_IAM;
+        aws cloudformation wait stack-update-complete --stack-name ApiDeploymentStack;
+      fi
+
+    # Deploy API Gateway stage
+    - REST_API_ID=$(aws cloudformation describe-stack-resource --stack-name ApiDeploymentStack --logical-resource-id myApiGateway --query "StackResourceDetail.PhysicalResourceId" --output text)
+    - if [ -n "$REST_API_ID" ]; then
+        aws apigateway create-deployment --rest-api-id $REST_API_ID --stage-name dev;
+      else
+        echo "API Gateway REST API ID not found"; exit 1;
+      fi
   only:
     - main
